# ---------------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
# ---------------------------------------------------------------------------

#Add new log path to be saved during graceful shutdown in below format:
# log_path<one space>filename
#where, log_path is path of log file to be saved and
#filename is name with which log will be saved

#ab-updater logs
/data/abupdater/ab-updater.log abupdater
/data/abupdater/ab-updater_old.log abupdater_last_boot

#ipc logs
/sys/kernel/debug/ipc_logging/csm_mtip/log mtip
/sys/kernel/debug/ipc_logging/csm_mtip_low/log mtip_low
/sys/kernel/debug/ipc_logging/qcom_aw_phy/log phy
/sys/kernel/debug/ipc_logging/ecpriss_core/log ecpri_log
/sys/kernel/debug/ipc_logging/ecpriss_core_cfg/log ecpri_cfg_log
/sys/kernel/debug/ipc_logging/ecpri_dma/log ecpri_dma
/sys/kernel/debug/ipc_logging/gsi/log gsi
/sys/kernel/debug/ipc_logging/ldmm/log ldmm

#transceiver logs
/sys/kernel/debug/ipc_logging/fpc-qsfp/log sfp

#/var/log
/var/log/epe.log epe
/var/log/faultmgr.log faultmgr
/var/log/pwrmgr.log pwrmgr
/var/log/si5518_image_dload_util.log si5518_image_dload_util
/var/log/splane_time_sync.log splane_time_sync
/var/log/synctimingdriver.log synctimingdriver
/var/log/synctimingptp2.log synctimingptp2
/var/log/messages syslog

#QNCM logs
/persist/qncm/qncm_log_0.txt qncm_log_0
/persist/qncm/qncm_bootup_log_0.txt qncm_bootup_log_0
/persist/qncm/qncm_log_1.txt qncm_log_1
/persist/qncm/qncm_bootup_log_1.txt qncm_bootup_log_1
/persist/qncm/qncm_log_2.txt qncm_log_2
/persist/qncm/qncm_bootup_log_2.txt qncm_bootup_log_2
/persist/qncm/qncm_log_3.txt qncm_log_3
/persist/qncm/qncm_bootup_log_3.txt qncm_bootup_log_3
/persist/qncm/qncm_log_4.txt qncm_log_4
/persist/qncm/qncm_bootup_log_4.txt qncm_bootup_log_4
/persist/qncm/qnetmgr_persistent_cfg_qru.xml qnetmgr_persistent_cfg_qru

